### ISSUE TITLE
comp/form_scope.t failing due to pad issue?

### ISSUE THREAD

**Issue by toddr** [CpanelInc/perl-compiler#35]
segfaults
```
sub f ($) { my $test = $_[0]; write;
format STDOUT =
ok @<<<<<<<
$test
.
} f(1);

**Comment by toddr** [comment]
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff78067bf in S_cv_clone_pad (proto=0x649778 <sv_list+312>, cv=0x679df0, outside=0x0, cloned=0x0, newcv=true) at pad.c:1957
1957		if ((CvCLONE(outside) && ! CvCLONED(outside))

(gdb) bt
#0  0x00007ffff78067bf in S_cv_clone_pad (proto=0x649778 <sv_list+312>, cv=0x679df0, outside=0x0, cloned=0x0, newcv=true) at pad.c:1957
#1  0x00007ffff7807d40 in S_cv_clone (proto=0x649778 <sv_list+312>, cv=0x679df0, outside=0x0, cloned=0x0) at pad.c:2264
#2  0x00007ffff7807da8 in Perl_cv_clone (proto=0x649778 <sv_list+312>) at pad.c:2282
#3  0x00007ffff78f03be in S_doform (cv=0x649778 <sv_list+312>, gv=0x648520 <gv_list+96>, retop=0x61b0e0 <unop_list>) at pp_sys.c:1390
#4  0x00007ffff78f06da in Perl_pp_enterwrite () at pp_sys.c:1438
#5  0x00007ffff788059b in Perl_runops_standard () at run.c:41
#6  0x00007ffff77ba477 in S_run_body (oldscope=1) at perl.c:2485
#7  0x00007ffff77b9f54 in perl_run (my_perl=0x657c70 <BC_unthreaded_interpreter>) at perl.c:2408
#8  0x000000000040c28d in main (argc=1, argv=0x7fffffffe298, env=0x7fffffffe2a8) at /usr/local/cpanel/B-C/t/v5.24.1/t/comp/form_scope.c:12639

**Comment by toddr** [comment]
This has been fixed for a while. the expected output was wrong so I don't have a root fix. Happened prior to 2f4a6ac2ad087568c110b762eca274c7d2794023
