### ISSUE TITLE
SEGV when Assigning a glob-with-sub to a glob that has lost its stash

### ISSUE THREAD

**Issue by atoomic** [CpanelInc/perl-compiler#37]
#The Devel::Peek here is just to illustrate that the stash is not removed from $x when deleting it.

```perl
#!./perl

# Assigning a glob-with-sub to a glob that has lost its stash works
# extract from op/gv.t

our $x;
our $glob;

$x = eval {
    sub greck;
    $glob = \*phing::foo;
    delete $::{"phing::"};
    *$glob = *greck;
};

eval q{use Devel::Peek; Dump($x) };

undef $x;
print qq{ok\n};
```

Output from uncompile & compile code
```
> configure.524; rm -f ./mygv; perl mygv.t && perlcc -v4 -g -S mygv.t; ./mygv
Check: ok
Makefile.PL: ok
Make: ok
SV = PVGV(0x661cf0) at 0x6699e8
  REFCNT = 1
  FLAGS = (FAKE,MULTI,IMPORTALL)
  NAME = "foo"
  NAMELEN = 3
  GvSTASH = 0x0
  FLAGS = 0xf2
  GP = 0x66f730
    SV = 0x0
    REFCNT = 3
    IO = 0x0
    FORM = 0x0
    AV = 0x0
    HV = 0x0
    CV = 0x669ac0
    CVGEN = 0x0
    GPFLAGS = 0x0 ()
    LINE = 12
    FILE = "mygv.t"
    EGV = 0x669a90	"greck"
ok
/usr/local/cpanel/3rdparty/perl/524/bin/perlcc: Using gcc '-g' compilation option.
/usr/local/cpanel/3rdparty/perl/524/bin/perlcc: Writing C on mygv.t.c
/usr/local/cpanel/3rdparty/perl/524/bin/perlcc: Calling /usr/local/cpanel/3rdparty/perl/524/bin/perl -I/root/.dotfiles/perl-must-have/lib -I/root/perl5/lib/perl5/ -I/usr/local/cpanel -MO=C,-omygv.t.c mygv.t
/usr/local/cpanel/3rdparty/perl/524/bin/perlcc: Calling /usr/bin/gcc -g  -DPERL_DISABLE_PMC -fPIC -DPIC -I/usr/local/cpanel/3rdparty/perl/524/include -L/usr/local/cpanel/3rdparty/perl/524/lib64 -I/usr/local/cpanel/3rdparty/include -L/usr/local/cpanel/3rdparty/lib64 -m64 -fwrapv -fno-strict-aliasing -fstack-protector-strong -I/usr/local/cpanel/3rdparty/include -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64  -I/usr/local/cpanel/3rdparty/perl/524/lib64/perl5/5.24.1/x86_64-linux-64int/CORE  -o ./mygv mygv.t.c  -Wl,-E -Wl,-rpath,/usr/local/cpanel/3rdparty/perl/524/lib64/perl5/5.24.1/x86_64-linux-64int/CORE -Wl,-rpath -Wl,/usr/local/cpanel/3rdparty/perl/524/lib64 -L/usr/local/cpanel/3rdparty/perl/524/lib64 -L/usr/local/cpanel/3rdparty/lib64 -L/usr/local/cpanel/3rdparty/perl/524/lib64 -L/usr/local/cpanel/3rdparty/lib64 -L/usr/lib64 -L/lib64 -lgdbm -fstack-protector-strong -L/usr/local/lib  -L/usr/local/cpanel/3rdparty/perl/524/lib64/perl5/5.24.1/x86_64-linux-64int/CORE /usr/local/cpanel/3rdparty/perl/524/lib64/perl5/5.24.1/x86_64-linux-64int/CORE/libperl.so -lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
SV = PVGV(0x1c47ea0) at 0x62e820
  REFCNT = 1
  FLAGS = (FAKE,MULTI,IMPORTALL)
  NAME = "foo"
  NAMELEN = 3
  GvSTASH = 0x62f9d8	"phing"
  FLAGS = 0xf2
  GP = 0x630e60
    SV = 0x0
    REFCNT = 4
    IO = 0x0
    FORM = 0x0
    AV = 0x0
    HV = 0x0
    CV = 0x6289b8
    CVGEN = 0x0
    GPFLAGS = 0x0 ()
    LINE = 12
    FILE = "mygv.t"
    EGV = 0x62fba0	"greck"
Segmentation fault
```

**Comment by atoomic** [comment]
When inspecting an uncompiled perl, it appears that stash is cleared when calling Perl_hv_kill_backrefs

```
$3021 = (HV *) 0x624858
#0  Perl_sv_kill_backrefs (sv=0x624858, av=0x624810) at sv.c:6169
#1  0x00007ffff787bdc3 in Perl_hv_kill_backrefs (hv=0x624858) at hv.c:2522
#2  0x00007ffff789f49b in Perl_sv_clear (orig_sv=0x624858) at sv.c:6462
#3  0x00007ffff78a0f5f in Perl_sv_free2 (sv=0x624858, rc=1) at sv.c:6955
#4  0x00007ffff77c131b in S_SvREFCNT_dec (sv=0x624858) at inline.h:166
#5  0x00007ffff77c991d in Perl_gp_free (gv=0x624888) at gv.c:2573
#6  0x00007ffff789fde1 in Perl_sv_clear (orig_sv=0x624888) at sv.c:6584
#7  0x00007ffff78a0f5f in Perl_sv_free2 (sv=0x624888, rc=1) at sv.c:6955
#8  0x00007ffff78d0d4b in S_SvREFCNT_dec_NN (sv=0x624888) at inline.h:177
#9  0x00007ffff78d15fe in Perl_free_tmps () at scope.c:203
#10 0x00007ffff788100b in Perl_pp_nextstate () at pp_hot.c:52
#11 0x00007ffff788059b in Perl_runops_standard () at run.c:41
#12 0x00007ffff77ba477 in S_run_body (oldscope=1) at perl.c:2485
#13 0x00007ffff77b9f54 in perl_run (my_perl=0x603010) at perl.c:2408
#14 0x0000000000400f5f in main (argc=2, argv=0x7fffffffdce8, env=0x7fffffffdd00) at perlmain.c:116
6193            if (is_array)
$3022 = (HV *) 0x0
#0  Perl_sv_kill_backrefs (sv=0x624858, av=0x624810) at sv.c:6193
#1  0x00007ffff787bdc3 in Perl_hv_kill_backrefs (hv=0x624858) at hv.c:2522
#2  0x00007ffff789f49b in Perl_sv_clear (orig_sv=0x624858) at sv.c:6462
#3  0x00007ffff78a0f5f in Perl_sv_free2 (sv=0x624858, rc=1) at sv.c:6955
#4  0x00007ffff77c131b in S_SvREFCNT_dec (sv=0x624858) at inline.h:166
#5  0x00007ffff77c991d in Perl_gp_free (gv=0x624888) at gv.c:2573
#6  0x00007ffff789fde1 in Perl_sv_clear (orig_sv=0x624888) at sv.c:6584
#7  0x00007ffff78a0f5f in Perl_sv_free2 (sv=0x624888, rc=1) at sv.c:6955
#8  0x00007ffff78d0d4b in S_SvREFCNT_dec_NN (sv=0x624888) at inline.h:177
#9  0x00007ffff78d15fe in Perl_free_tmps () at scope.c:203
#10 0x00007ffff788100b in Perl_pp_nextstate () at pp_hot.c:52
#11 0x00007ffff788059b in Perl_runops_standard () at run.c:41
#12 0x00007ffff77ba477 in S_run_body (oldscope=1) at perl.c:2485
#13 0x00007ffff77b9f54 in perl_run (my_perl=0x603010) at perl.c:2408
#14 0x0000000000400f5f in main (argc=2, argv=0x7fffffffdce8, env=0x7fffffffdd00) at perlmain.c:116
```

Dummy helper for gdb
```
set max-user-call-depth 99999999
# then
define sss
set $st = ( (GV*) 0x624810 )->sv_any->xnv_u.xgv_stash
p $st
where
if ( $st )
step
sss
end
end
```

**Comment by atoomic** [comment]
Two things there... we are using a refcnt + 1, and we are not saving the backref...

**Comment by toddr** [comment]
fixed.
